### ISSUE TITLE
Error on logout (only valid absolute URLs can be requested)

### ISSUE THREAD

**Issue by edwardchanjw** [sdoxsee/cats-nest#5]
Learning the flow of OAuth and OpenID in NestJS

OAuth 2.0 Client IDs

```
OAUTH2_CLIENT_REGISTRATION_LOGIN_REDIRECT_URI=https://jsnodetest-onstarrynight685392.codeanyapp.com/callback
OAUTH2_CLIENT_REGISTRATION_LOGIN_POST_LOGOUT_REDIRECT_URI=https://jsnodetest-onstarrynight685392.codeanyapp.com/logout
```
I tried OAUTH2_CLIENT_REGISTRATION_LOGIN_POST_LOGOUT_REDIRECT_URI for https://jsnodetest-onstarrynight685392.codeanyapp.com, https://jsnodetest-onstarrynight685392.codeanyapp.com/, https://jsnodetest-onstarrynight685392.codeanyapp.com/logout, 

Anything that the error would occur? 

(node:1185) UnhandledPromiseRejectionWarning: TypeError: only valid absolute URLs can be requested
    at module.exports (/home/cabox/workspace/cats-nest/back-end/node_modules/openid-client/lib/helpers/is_absolute_url.js:10:11)
    at Function.request (/home/cabox/workspace/cats-nest/back-end/node_modules/openid-client/lib/helpers/request.js:27:3)
    at Function.discover (/home/cabox/workspace/cats-nest/back-end/node_modules/openid-client/lib/issuer.js:215:38)
    at req.session.destroy (/home/cabox/workspace/cats-nest/back-end/dist/auth/auth.controller.js:30:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1185) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:1185) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by edwardchanjw** [comment]
I am missing the first line, the code refer google, but the example mention OIDC, and I though I filled.

```
OAUTH2_CLIENT_PROVIDER_GOOGLE_ISSUER=https://accounts.google.com
OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER=https://accounts.google.com
OAUTH2_CLIENT_REGISTRATION_LOGIN_CLIENT_ID=
OAUTH2_CLIENT_REGISTRATION_LOGIN_CLIENT_SECRET=
OAUTH2_CLIENT_REGISTRATION_LOGIN_SCOPE=openid profile
OAUTH2_CLIENT_REGISTRATION_LOGIN_REDIRECT_URI=
OAUTH2_CLIENT_REGISTRATION_LOGIN_POST_LOGOUT_REDIRECT_URI=
SESSION_SECRET=
MONGODB_URL=

```
